tests/.oomph-cache/.../bad_noreturn_func_error: noreturn was used, but foo() still returned
Program exited with status 1
